Retry on failed connects
- Fix all go vet issues

[#69786534]

Signed-off-by: Matthew Sykes <matthew.sykes@gmail.com>

Conflicts:
	proxy/proxy.go
	proxy/proxy_test.go
	proxy/request_handler.go
	scripts/test

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -2,7 +2,18 @@
 
 set -e -x -u
 
+
 export DROPSONDE_ORIGIN="gorouter_test/0"
+
+function printStatus {
+      if [ $? -eq 0 ]; then
+          echo -e "\nSWEET SUITE SUCCESS"
+      else
+          echo -e "\nSUITE FAILURE"
+      fi
+  }
+
+trap printStatus EXIT
 
 . $(dirname $0)/gorequired
 
